version: '3'
services:
  fastapi:
    container_name: endpoints
    build:
      context: ./src
    restart: always
    env_file:
    - .env
    depends_on:
      - postgres
#        condition: service_healthy
    ports:
      - "2048:2048"
  postgres:
    image: postgres:latest
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "${POSTGRES_LOCAL_PORT}:5432"
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
#      interval: 5s
#      timeout: 10s
#      retries: 10
#      start_period: 10s
    volumes:
      - ./postgres_data:/var/lib/postgresql/data