version: '3'
services:
  web:
    container_name: endpoints
    build:
      context: ./src
    restart: always
    env_file:
    - .env
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "${POSTGRES_LOCAL_PORT}:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data