version: '3'
services:
  fastapi:
    container_name: endpoints
    build:
      context: ./src
    restart: always
    env_file:
    - .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "2048:2048"
  postgres:
    image: postgres:latest
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "${POSTGRES_LOCAL_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB}" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    volumes:
      - ./postgres_data:/var/lib/postgresql/data